services:
  judge:
    image: ghcr.io/forklifts-for-great-justice/judge-service:main
    container_name: judge
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - scoreboard
    labels:
      - "proxy.enable=true"
      - "proxy.host=judge.hackfortress.net"
      - "proxy.port=8086"
      - "proxy.auth_required=true"
      - "proxy.client_id=judge-client"
      - "proxy.openapi_path=/openapi.json"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PORT=8086
      - DB_DSN=postgres://scoreboard:changeme@scoreboard.hackfortress.net:5432/hackfortress?sslmode=disable
      - RABBITMQ_URL=amqp://admin:adminpassword@admin.hackfortress.net:5672
      - RABBITMQ_EXCHANGE=hackfortress

networks:
  scoreboard:
    external:
      name: scoreboard
