services:
  judge:
    image: ghcr.io/forklifts-for-great-justice/judge-service:main
    container_name: judge
    restart: unless-stopped
    networks:
      - scoreboard_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PORT=8086
      - DB_DSN=postgres://scoreboard:changeme@postgres:5432/hackfortress?sslmode=disable
      - RABBITMQ_URL=amqp://admin:adminpassword@admin.hackfortress.net:5672
      - RABBITMQ_EXCHANGE=hackfortress

networks:
  scoreboard_network:
    external:
      name: scoreboard_scoreboard
